version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    volumes:
      - ./config:/home/ditto/config
      - ./apps/ditto_bot/lib:/home/ditto/apps/ditto_bot/lib
      - ./mix.exs:/home/ditto/mix.exs
      - ./mix.lock:/home/ditto/mix.lock
      - ./apps/ditto_bot/test:/home/ditto/apps/ditto_bot/test
      - ./apps/ditto_bot/mix.exs:/home/ditto/apps/ditto_bot/mix.exs
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports: 
      - 4000:4000
    volumes:
      - ./config:/home/ditto/config
      - ./apps/ditto_api/lib:/home/ditto/apps/ditto_api/lib
      - ./mix.exs:/home/ditto/mix.exs
      - ./mix.lock:/home/ditto/mix.lock
      - ./apps/ditto_api/test:/home/ditto/apps/ditto_api/test
      - ./apps/ditto_api/mix.exs:/home/ditto/apps/ditto_api/mix.exs
    stdin_open: true
    tty: true
