version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  base:
    image: ridhoq/ditto/base
    build:
      context: .
      dockerfile: Dockerfile.base
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    volumes:
      - ./config:/home/ditto/config
      - ./apps/ditto_bot/lib:/home/ditto/apps/ditto_bot/lib
      - ./mix.exs:/home/ditto/mix.exs
      - ./mix.lock:/home/ditto/mix.lock
      - ./apps/ditto_bot/test:/home/ditto/apps/ditto_bot/test
      - ./apps/ditto_bot/mix.exs:/home/ditto/apps/ditto_bot/mix.exs
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports: 
      - 4000:4000
    volumes:
      - ./config:/home/ditto/config
      - ./apps/ditto_api/lib:/home/ditto/apps/ditto_api/lib
      - ./mix.exs:/home/ditto/mix.exs
      - ./mix.lock:/home/ditto/mix.lock
      - ./apps/ditto_api/test:/home/ditto/apps/ditto_api/test
      - ./apps/ditto_api/mix.exs:/home/ditto/apps/ditto_api/mix.exs
    depends_on:
      - kafka
    stdin_open: true
    tty: true
  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    env_file: .env
    volumes:
        - ./config:/home/ditto/config
        - ./apps/ditto_kafka/lib:/home/ditto/apps/ditto_kafka/lib
        - ./mix.exs:/home/ditto/mix.exs
        - ./mix.lock:/home/ditto/mix.lock
        - ./apps/ditto_kafka/test:/home/ditto/apps/ditto_kafka/test
        - ./apps/ditto_kafka/mix.exs:/home/ditto/apps/ditto_kafka/mix.exs
    depends_on:
      - kafka_broker
  kafka_broker:
    image: wurstmeister/kafka
    env_file: .env
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

