import os

COSMOS_ACCOUNT_URI = os.getenv('COSMOS_ACCOUNT_URI')
COSMOS_ACCOUNT_KEY = os.getenv('COSMOS_ACCOUNT_KEY')
COSMOS_DATABASE_ID = os.getenv('COSMOS_DATABASE_ID')
AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
COSMOS_ENABLE_TLS = os.getenv('COSMOS_ENABLE_TLS')
