version: '3.7'

services:
  cli:
    build:
      context: .
      target: production
    image: ridhoq/ditto/ditto-markov
    env_file: .env
    volumes:
      - ./ditto_markov:/app/ditto_markov
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    entrypoint: ["poetry", "run", "cli",]