version: '3.7'

services:
  cli:
    build:
      context: .
      target: production
    image: ridhoq/ditto/ditto-markov
    env_file: .env
    volumes:
      - ./ditto_markov:/app/ditto_markov
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    entrypoint: ["poetry", "run", "cli",]

  cosmosdb:
    image: ridhoq/cosmosdb-server:0.7.0
    command: ["-p", "3000"]
    ports:
    - 3000
    
  test:
    depends_on:
      - cosmosdb
    build:
      context: .
      target: development
    image: ridhoq/ditto/ditto-markov/test
    environment:
      COSMOS_ACCOUNT_URI: https://cosmosdb:3000/
      COSMOS_DATABASE_ID: ditto-test
      COSMOS_ACCOUNT_KEY: ''
      COSMOS_ENABLE_TLS: "False"
    volumes:
      - ./ditto_markov:/app/ditto_markov
      - ./tests:/app/tests
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    command: ["pytest"]
