version: '3.7'

services:
  cli:
    build:
      context: .
      target: production
    image: ridhoq/ditto/ditto-markov
    env_file: .env
    volumes:
      - ./ditto_markov:/app/ditto_markov
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    entrypoint: ["poetry", "run", "cli",]
    
  api:
    build:
      context: .
      target: production
    image: ridhoq/ditto/ditto-markov
    env_file: .env
    environment:
      APP_MODULE: ditto_markov.api:api
      PORT: 8888
    ports:
      - 8888:8888
    volumes:
      - ./ditto_markov:/app/ditto_markov
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml

  cosmosdb:
    image: ridhoq/cosmosdb-server:0.7.0
    command: ["-p", "3000"]
    ports:
    - 3000
      
  blob:
    image: mcr.microsoft.com/azure-storage/azurite:3.7.0
    ports:
      - 10000
    
  test:
    depends_on:
      - cosmosdb
      - blob
    build:
      context: .
      target: development
    image: ridhoq/ditto/ditto-markov/test
    environment:
      COSMOS_ACCOUNT_URI: https://cosmosdb:3000
      COSMOS_DATABASE_ID: ditto-test
      COSMOS_DISABLE_TLS: "True"
      # default conn str from https://github.com/Azure/Azurite#http-connection-strings
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://blob:10000/devstoreaccount1;"
    volumes:
      - ./pytest.ini:/app/pytest.ini
      - ./ditto_markov:/app/ditto_markov
      - ./tests:/app/tests
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    command: ["pytest"]
