name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ditto.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: |
        cd ditto-markov
        cp .env.example .env
        docker-compose build
    - name: Run the tests
      run: |
        cd ditto-markov
        docker-compose run test
    - name: Push image to ACR
      if: github.ref == 'refs/heads/api'
      run: |
        docker tag ridhoq/ditto/ditto-markov ditto.azurecr.io/ditto:${{github.ref}}-${{github.sha}}
        docker tag ridhoq/ditto/ditto-markov ditto.azurecr.io/ditto:${{github.ref}}-latest
        docker push ridhoq/ditto/ditto-markov ditto.azurecr.io/ditto:${{github.ref}}-${{github.sha}}
        docker push ridhoq/ditto/ditto-markov ditto.azurecr.io/ditto:${{github.ref}}-latest
